# This file has been generated by node2nix 1.9.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@types/accepts-1.3.5" = {
      name = "_at_types_slash_accepts";
      packageName = "@types/accepts";
      version = "1.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/accepts/-/accepts-1.3.5.tgz";
        sha512 = "jOdnI/3qTpHABjM5cx1Hc0sKsPoYCp+DP/GJRGtDlPd7fiV9oXGGIcjW/ZOxLIvjGz8MA+uMZI9metHlgqbgwQ==";
      };
    };
    "@types/body-parser-1.19.0" = {
      name = "_at_types_slash_body-parser";
      packageName = "@types/body-parser";
      version = "1.19.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/body-parser/-/body-parser-1.19.0.tgz";
        sha512 = "W98JrE0j2K78swW4ukqMleo8R7h/pFETjM2DQ90MF6XK2i4LO4W3gQ71Lt4w3bfm2EvVSyWHplECvB5sK22yFQ==";
      };
    };
    "@types/collections-5.0.0" = {
      name = "_at_types_slash_collections";
      packageName = "@types/collections";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/collections/-/collections-5.0.0.tgz";
        sha512 = "hP3yPM7ePW89pKcVCnCTnzSaKdr7QQaz/fGfj8YUSIbWAmvNM/QVRWXpmh7bh19u2x006FPWBHow6ZX3zOL5lA==";
      };
    };
    "@types/connect-3.4.34" = {
      name = "_at_types_slash_connect";
      packageName = "@types/connect";
      version = "3.4.34";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/connect/-/connect-3.4.34.tgz";
        sha512 = "ePPA/JuI+X0vb+gSWlPKOY0NdNAie/rPUqX2GUPpbZwiKTkSPhjXWuee47E4MtE54QVzGCQMQkAL6JhV2E1+cQ==";
      };
    };
    "@types/content-disposition-0.5.3" = {
      name = "_at_types_slash_content-disposition";
      packageName = "@types/content-disposition";
      version = "0.5.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/content-disposition/-/content-disposition-0.5.3.tgz";
        sha512 = "P1bffQfhD3O4LW0ioENXUhZ9OIa0Zn+P7M+pWgkCKaT53wVLSq0mrKksCID/FGHpFhRSxRGhgrQmfhRuzwtKdg==";
      };
    };
    "@types/cookies-0.7.6" = {
      name = "_at_types_slash_cookies";
      packageName = "@types/cookies";
      version = "0.7.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/cookies/-/cookies-0.7.6.tgz";
        sha512 = "FK4U5Qyn7/Sc5ih233OuHO0qAkOpEcD/eG6584yEiLKizTFRny86qHLe/rej3HFQrkBuUjF4whFliAdODbVN/w==";
      };
    };
    "@types/express-4.17.11" = {
      name = "_at_types_slash_express";
      packageName = "@types/express";
      version = "4.17.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/express/-/express-4.17.11.tgz";
        sha512 = "no+R6rW60JEc59977wIxreQVsIEOAYwgCqldrA/vkpCnbD7MqTefO97lmoBe4WE0F156bC4uLSP1XHDOySnChg==";
      };
    };
    "@types/express-serve-static-core-4.17.19" = {
      name = "_at_types_slash_express-serve-static-core";
      packageName = "@types/express-serve-static-core";
      version = "4.17.19";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/express-serve-static-core/-/express-serve-static-core-4.17.19.tgz";
        sha512 = "DJOSHzX7pCiSElWaGR8kCprwibCB/3yW6vcT8VG3P0SJjnv19gnWG/AZMfM60Xj/YJIp/YCaDHyvzsFVeniARA==";
      };
    };
    "@types/http-assert-1.5.1" = {
      name = "_at_types_slash_http-assert";
      packageName = "@types/http-assert";
      version = "1.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/http-assert/-/http-assert-1.5.1.tgz";
        sha512 = "PGAK759pxyfXE78NbKxyfRcWYA/KwW17X290cNev/qAsn9eQIxkH4shoNBafH37wewhDG/0p1cHPbK6+SzZjWQ==";
      };
    };
    "@types/http-errors-1.8.0" = {
      name = "_at_types_slash_http-errors";
      packageName = "@types/http-errors";
      version = "1.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/http-errors/-/http-errors-1.8.0.tgz";
        sha512 = "2aoSC4UUbHDj2uCsCxcG/vRMXey/m17bC7UwitVm5hn22nI8O8Y9iDpA76Orc+DWkQ4zZrOKEshCqR/jSuXAHA==";
      };
    };
    "@types/keygrip-1.0.2" = {
      name = "_at_types_slash_keygrip";
      packageName = "@types/keygrip";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/keygrip/-/keygrip-1.0.2.tgz";
        sha512 = "GJhpTepz2udxGexqos8wgaBx4I/zWIDPh/KOGEwAqtuGDkOUJu5eFvwmdBX4AmB8Odsr+9pHCQqiAqDL/yKMKw==";
      };
    };
    "@types/koa-2.13.1" = {
      name = "_at_types_slash_koa";
      packageName = "@types/koa";
      version = "2.13.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/koa/-/koa-2.13.1.tgz";
        sha512 = "Qbno7FWom9nNqu0yHZ6A0+RWt4mrYBhw3wpBAQ3+IuzGcLlfeYkzZrnMq5wsxulN2np8M4KKeUpTodsOsSad5Q==";
      };
    };
    "@types/koa-compose-3.2.5" = {
      name = "_at_types_slash_koa-compose";
      packageName = "@types/koa-compose";
      version = "3.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/koa-compose/-/koa-compose-3.2.5.tgz";
        sha512 = "B8nG/OoE1ORZqCkBVsup/AKcvjdgoHnfi4pZMn5UwAPCbhk/96xyv284eBYW8JlQbQ7zDmnpFr68I/40mFoIBQ==";
      };
    };
    "@types/koa2-cors-2.0.1" = {
      name = "_at_types_slash_koa2-cors";
      packageName = "@types/koa2-cors";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/koa2-cors/-/koa2-cors-2.0.1.tgz";
        sha512 = "8DaO8CkGJGAVWPeODHeGW6T9grKunnfAg0LAyayMrqP/ggPTiHxwrvrk7UJ+NNZ7aQo4Cn0fHSMKhucj+PcquA==";
      };
    };
    "@types/mime-1.3.2" = {
      name = "_at_types_slash_mime";
      packageName = "@types/mime";
      version = "1.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/mime/-/mime-1.3.2.tgz";
        sha512 = "YATxVxgRqNH6nHEIsvg6k2Boc1JHI9ZbH5iWFFv/MTkchz3b1ieGDa5T0a9RznNdI0KhVbdbWSN+KWWrQZRxTw==";
      };
    };
    "@types/node-14.14.37" = {
      name = "_at_types_slash_node";
      packageName = "@types/node";
      version = "14.14.37";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/node/-/node-14.14.37.tgz";
        sha512 = "XYmBiy+ohOR4Lh5jE379fV2IU+6Jn4g5qASinhitfyO71b/sCo6MKsMLF5tc7Zf2CE8hViVQyYSobJNke8OvUw==";
      };
    };
    "@types/node-fetch-2.5.7" = {
      name = "_at_types_slash_node-fetch";
      packageName = "@types/node-fetch";
      version = "2.5.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/node-fetch/-/node-fetch-2.5.7.tgz";
        sha512 = "o2WVNf5UhWRkxlf6eq+jMZDu7kjgpgJfl4xVNlvryc95O/6F2ld8ztKX+qu+Rjyet93WAWm5LjeX9H5FGkODvw==";
      };
    };
    "@types/qs-6.9.6" = {
      name = "_at_types_slash_qs";
      packageName = "@types/qs";
      version = "6.9.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/qs/-/qs-6.9.6.tgz";
        sha512 = "0/HnwIfW4ki2D8L8c9GVcG5I72s9jP5GSLVF0VIXDW00kmIpA6O33G7a8n59Tmh7Nz0WUC3rSb7PTY/sdW2JzA==";
      };
    };
    "@types/range-parser-1.2.3" = {
      name = "_at_types_slash_range-parser";
      packageName = "@types/range-parser";
      version = "1.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/range-parser/-/range-parser-1.2.3.tgz";
        sha512 = "ewFXqrQHlFsgc09MK5jP5iR7vumV/BYayNC6PgJO2LPe8vrnNFyjQjSppfEngITi0qvfKtzFvgKymGheFM9UOA==";
      };
    };
    "@types/serve-static-1.13.9" = {
      name = "_at_types_slash_serve-static";
      packageName = "@types/serve-static";
      version = "1.13.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/serve-static/-/serve-static-1.13.9.tgz";
        sha512 = "ZFqF6qa48XsPdjXV5Gsz0Zqmux2PerNd3a/ktL45mHpa19cuMi/cL8tcxdAx497yRh+QtYPuofjT9oWw9P7nkA==";
      };
    };
    "accepts-1.3.7" = {
      name = "accepts";
      packageName = "accepts";
      version = "1.3.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/accepts/-/accepts-1.3.7.tgz";
        sha512 = "Il80Qs2WjYlJIBNzNkK6KYqlVMTbZLXgHx2oT0pU/fjRHyEp+PEfEPY0R3WCwAGVOtauxh1hOxNgIf5bv7dQpA==";
      };
    };
    "any-promise-1.3.0" = {
      name = "any-promise";
      packageName = "any-promise";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/any-promise/-/any-promise-1.3.0.tgz";
        sha1 = "abc6afeedcea52e809cdc0376aed3ce39635d17f";
      };
    };
    "asynckit-0.4.0" = {
      name = "asynckit";
      packageName = "asynckit";
      version = "0.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/asynckit/-/asynckit-0.4.0.tgz";
        sha1 = "c79ed97f7f34cb8f2ba1bc9790bcc366474b4b79";
      };
    };
    "buffer-from-1.1.1" = {
      name = "buffer-from";
      packageName = "buffer-from";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-from/-/buffer-from-1.1.1.tgz";
        sha512 = "MQcXEUbCKtEo7bhqEs6560Hyd4XaovZlO/k9V3hjVUF/zwW7KBVdSK4gIt/bzwS9MbR5qob+F5jusZsb0YQK2A==";
      };
    };
    "cache-content-type-1.0.1" = {
      name = "cache-content-type";
      packageName = "cache-content-type";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/cache-content-type/-/cache-content-type-1.0.1.tgz";
        sha512 = "IKufZ1o4Ut42YUrZSo8+qnMTrFuKkvyoLXUywKz9GJ5BrhOFGhLdkx9sG4KAnVvbY6kEcSFjLQul+DVmBm2bgA==";
      };
    };
    "co-4.6.0" = {
      name = "co";
      packageName = "co";
      version = "4.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/co/-/co-4.6.0.tgz";
        sha1 = "6ea6bdf3d853ae54ccb8e47bfa0bf3f9031fb184";
      };
    };
    "collections-5.1.2" = {
      name = "collections";
      packageName = "collections";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/collections/-/collections-5.1.2.tgz";
        sha512 = "hG01lBeGUdQcUvkzYz6CdLIQqMkFIF40+mLmuy81JgC9+CelKFfA213DnvrNeUWTNGILGKOFVLK6OltDB/XIwg==";
      };
    };
    "combined-stream-1.0.8" = {
      name = "combined-stream";
      packageName = "combined-stream";
      version = "1.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/combined-stream/-/combined-stream-1.0.8.tgz";
        sha512 = "FQN4MRfuJeHf7cBbBMJFXhKSDq+2kAArBlmRBvcvFE5BB1HZKXtSFASDhdlz9zOYwxh8lDdnvmMOe/+5cdoEdg==";
      };
    };
    "content-disposition-0.5.3" = {
      name = "content-disposition";
      packageName = "content-disposition";
      version = "0.5.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/content-disposition/-/content-disposition-0.5.3.tgz";
        sha512 = "ExO0774ikEObIAEV9kDo50o+79VCUdEB6n6lzKgGwupcVeRlhrj3qGAfwq8G6uBJjkqLrhT0qEYFcWng8z1z0g==";
      };
    };
    "content-type-1.0.4" = {
      name = "content-type";
      packageName = "content-type";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/content-type/-/content-type-1.0.4.tgz";
        sha512 = "hIP3EEPs8tB9AT1L+NUqtwOAps4mk2Zob89MWXMHjHWg9milF/j4osnnQLXBCBFBk/tvIG/tUc9mOUJiPBhPXA==";
      };
    };
    "cookies-0.8.0" = {
      name = "cookies";
      packageName = "cookies";
      version = "0.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cookies/-/cookies-0.8.0.tgz";
        sha512 = "8aPsApQfebXnuI+537McwYsDtjVxGm8gTIzQI3FDW6t5t/DAhERxtnbEPN/8RX+uZthoz4eCOgloXaE5cYyNow==";
      };
    };
    "debug-3.1.0" = {
      name = "debug";
      packageName = "debug";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-3.1.0.tgz";
        sha512 = "OX8XqP7/1a9cqkxYw2yXss15f26NKWBpDXQd0/uK/KPqdQhxbPa994hnzjcE2VqQpDslf55723cKPUOGSmMY3g==";
      };
    };
    "deep-equal-1.0.1" = {
      name = "deep-equal";
      packageName = "deep-equal";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/deep-equal/-/deep-equal-1.0.1.tgz";
        sha1 = "f5d260292b660e084eff4cdbc9f08ad3247448b5";
      };
    };
    "delayed-stream-1.0.0" = {
      name = "delayed-stream";
      packageName = "delayed-stream";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/delayed-stream/-/delayed-stream-1.0.0.tgz";
        sha1 = "df3ae199acadfb7d440aaae0b29e2272b24ec619";
      };
    };
    "delegates-1.0.0" = {
      name = "delegates";
      packageName = "delegates";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/delegates/-/delegates-1.0.0.tgz";
        sha1 = "84c6e159b81904fdca59a0ef44cd870d31250f9a";
      };
    };
    "depd-1.1.2" = {
      name = "depd";
      packageName = "depd";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/depd/-/depd-1.1.2.tgz";
        sha1 = "9bcd52e14c097763e749b274c4346ed2e560b5a9";
      };
    };
    "depd-2.0.0" = {
      name = "depd";
      packageName = "depd";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/depd/-/depd-2.0.0.tgz";
        sha512 = "g7nH6P6dyDioJogAAGprGpCtVImJhpPk/roCzdb3fIh61/s/nPsfR6onyMwkCAR/OlC3yBC0lESvUoQEAssIrw==";
      };
    };
    "destroy-1.0.4" = {
      name = "destroy";
      packageName = "destroy";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/destroy/-/destroy-1.0.4.tgz";
        sha1 = "978857442c44749e4206613e37946205826abd80";
      };
    };
    "ee-first-1.1.1" = {
      name = "ee-first";
      packageName = "ee-first";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ee-first/-/ee-first-1.1.1.tgz";
        sha1 = "590c61156b0ae2f4f0255732a158b266bc56b21d";
      };
    };
    "encodeurl-1.0.2" = {
      name = "encodeurl";
      packageName = "encodeurl";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/encodeurl/-/encodeurl-1.0.2.tgz";
        sha1 = "ad3ff4c86ec2d029322f5a02c3a9a606c95b3f59";
      };
    };
    "escape-html-1.0.3" = {
      name = "escape-html";
      packageName = "escape-html";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-html/-/escape-html-1.0.3.tgz";
        sha1 = "0258eae4d3d0c0974de1c169188ef0051d1d1988";
      };
    };
    "ethereumjs-blockstream-7.0.0" = {
      name = "ethereumjs-blockstream";
      packageName = "ethereumjs-blockstream";
      version = "7.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ethereumjs-blockstream/-/ethereumjs-blockstream-7.0.0.tgz";
        sha512 = "lt3uLKDEfNHEqqnl/+W0aC7xp2y7JEsgZsJMZ958CNrYIJH9tZ7oa8npwV2M0KhGlfzmJsyJIpvV/Lvb2mh0tA==";
      };
    };
    "form-data-3.0.0" = {
      name = "form-data";
      packageName = "form-data";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/form-data/-/form-data-3.0.0.tgz";
        sha512 = "CKMFDglpbMi6PyN+brwB9Q/GOw0eAnsrEZDgcsH5Krhz5Od/haKHAX0NmQfha2zPPz0JpWzA7GJHGSnvCRLWsg==";
      };
    };
    "fresh-0.5.2" = {
      name = "fresh";
      packageName = "fresh";
      version = "0.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/fresh/-/fresh-0.5.2.tgz";
        sha1 = "3d8cadd90d976569fa835ab1f8e4b23a105605a7";
      };
    };
    "http-assert-1.4.1" = {
      name = "http-assert";
      packageName = "http-assert";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-assert/-/http-assert-1.4.1.tgz";
        sha512 = "rdw7q6GTlibqVVbXr0CKelfV5iY8G2HqEUkhSk297BMbSpSL8crXC+9rjKoMcZZEsksX30le6f/4ul4E28gegw==";
      };
    };
    "http-errors-1.7.3" = {
      name = "http-errors";
      packageName = "http-errors";
      version = "1.7.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-errors/-/http-errors-1.7.3.tgz";
        sha512 = "ZTTX0MWrsQ2ZAhA1cejAwDLycFsd7I7nVtnkT3Ol0aqodaKW+0CTZDQ1uBv5whptCnc8e8HeRRJxRs0kmm/Qfw==";
      };
    };
    "http-errors-1.8.0" = {
      name = "http-errors";
      packageName = "http-errors";
      version = "1.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-errors/-/http-errors-1.8.0.tgz";
        sha512 = "4I8r0C5JDhT5VkvI47QktDW75rNlGVsUf/8hzjCC/wkWI/jdTRmBb9aI7erSG82r1bjKY3F6k28WnsVxB1C73A==";
      };
    };
    "immutable-3.8.2" = {
      name = "immutable";
      packageName = "immutable";
      version = "3.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/immutable/-/immutable-3.8.2.tgz";
        sha1 = "c2439951455bb39913daf281376f1530e104adf3";
      };
    };
    "inherits-2.0.4" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.4.tgz";
        sha512 = "k/vGaX4/Yla3WzyMCvTQOXYeIHvqOKtnqBduzTHpzpQZzAskKMhZ2K+EnBiSM9zGSoIFeMpXKxa4dYeZIQqewQ==";
      };
    };
    "is-generator-function-1.0.8" = {
      name = "is-generator-function";
      packageName = "is-generator-function";
      version = "1.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-generator-function/-/is-generator-function-1.0.8.tgz";
        sha512 = "2Omr/twNtufVZFr1GhxjOMFPAj2sjc/dKaIqBhvo4qciXfJmITGH6ZGd8eZYNHza8t1y0e01AuqRhJwfWp26WQ==";
      };
    };
    "keygrip-1.1.0" = {
      name = "keygrip";
      packageName = "keygrip";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/keygrip/-/keygrip-1.1.0.tgz";
        sha512 = "iYSchDJ+liQ8iwbSI2QqsQOvqv58eJCEanyJPJi+Khyu8smkcKSFUCbPwzFcL7YVtZ6eONjqRX/38caJ7QjRAQ==";
      };
    };
    "koa-2.13.1" = {
      name = "koa";
      packageName = "koa";
      version = "2.13.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/koa/-/koa-2.13.1.tgz";
        sha512 = "Lb2Dloc72auj5vK4X4qqL7B5jyDPQaZucc9sR/71byg7ryoD1NCaCm63CShk9ID9quQvDEi1bGR/iGjCG7As3w==";
      };
    };
    "koa-compose-3.2.1" = {
      name = "koa-compose";
      packageName = "koa-compose";
      version = "3.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/koa-compose/-/koa-compose-3.2.1.tgz";
        sha1 = "a85ccb40b7d986d8e5a345b3a1ace8eabcf54de7";
      };
    };
    "koa-compose-4.1.0" = {
      name = "koa-compose";
      packageName = "koa-compose";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/koa-compose/-/koa-compose-4.1.0.tgz";
        sha512 = "8ODW8TrDuMYvXRwra/Kh7/rJo9BtOfPc6qO8eAfC80CnCvSjSl0bkRM24X6/XBBEyj0v1nRUQ1LyOy3dbqOWXw==";
      };
    };
    "koa-convert-1.2.0" = {
      name = "koa-convert";
      packageName = "koa-convert";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/koa-convert/-/koa-convert-1.2.0.tgz";
        sha1 = "da40875df49de0539098d1700b50820cebcd21d0";
      };
    };
    "koa2-cors-2.0.5" = {
      name = "koa2-cors";
      packageName = "koa2-cors";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/koa2-cors/-/koa2-cors-2.0.5.tgz";
        sha1 = "3404712cd092f728c7f72de704ee7b920d957658";
      };
    };
    "media-typer-0.3.0" = {
      name = "media-typer";
      packageName = "media-typer";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/media-typer/-/media-typer-0.3.0.tgz";
        sha1 = "8710d7af0aa626f8fffa1ce00168545263255748";
      };
    };
    "mime-db-1.30.0" = {
      name = "mime-db";
      packageName = "mime-db";
      version = "1.30.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-db/-/mime-db-1.30.0.tgz";
        sha1 = "74c643da2dd9d6a45399963465b26d5ca7d71f01";
      };
    };
    "mime-db-1.47.0" = {
      name = "mime-db";
      packageName = "mime-db";
      version = "1.47.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-db/-/mime-db-1.47.0.tgz";
        sha512 = "QBmA/G2y+IfeS4oktet3qRZ+P5kPhCKRXxXnQEudYqUaEioAU1/Lq2us3D/t1Jfo4hE9REQPrbB7K5sOczJVIw==";
      };
    };
    "mime-types-2.1.17" = {
      name = "mime-types";
      packageName = "mime-types";
      version = "2.1.17";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-types/-/mime-types-2.1.17.tgz";
        sha1 = "09d7a393f03e995a79f8af857b70a9e0ab16557a";
      };
    };
    "mime-types-2.1.30" = {
      name = "mime-types";
      packageName = "mime-types";
      version = "2.1.30";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-types/-/mime-types-2.1.30.tgz";
        sha512 = "crmjA4bLtR8m9qLpHvgxSChT+XoSlZi8J4n/aIdn3z92e/U47Z0V/yl+Wh9W046GgFVAmoNR/fmdbZYcSSIUeg==";
      };
    };
    "ms-2.0.0" = {
      name = "ms";
      packageName = "ms";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.0.0.tgz";
        sha1 = "5608aeadfc00be6c2901df5f9861788de0d597c8";
      };
    };
    "negotiator-0.6.2" = {
      name = "negotiator";
      packageName = "negotiator";
      version = "0.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/negotiator/-/negotiator-0.6.2.tgz";
        sha512 = "hZXc7K2e+PgeI1eDBe/10Ard4ekbfrrqG8Ep+8Jmf4JID2bNg7NvCPOZN+kfF574pFQI7mum2AUqDidoKqcTOw==";
      };
    };
    "node-fetch-2.6.1" = {
      name = "node-fetch";
      packageName = "node-fetch";
      version = "2.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-fetch/-/node-fetch-2.6.1.tgz";
        sha512 = "V4aYg89jEoVRxRb2fJdAg8FHvI7cEyYdVAh94HH0UIK8oJxUfkjlDQN9RbMx+bEjP7+ggMiFRprSti032Oipxw==";
      };
    };
    "on-finished-2.3.0" = {
      name = "on-finished";
      packageName = "on-finished";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/on-finished/-/on-finished-2.3.0.tgz";
        sha1 = "20f1336481b083cd75337992a16971aa2d906947";
      };
    };
    "only-0.0.2" = {
      name = "only";
      packageName = "only";
      version = "0.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/only/-/only-0.0.2.tgz";
        sha1 = "2afde84d03e50b9a8edc444e30610a70295edfb4";
      };
    };
    "parseurl-1.3.3" = {
      name = "parseurl";
      packageName = "parseurl";
      version = "1.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/parseurl/-/parseurl-1.3.3.tgz";
        sha512 = "CiyeOxFT/JZyN5m0z9PfXw4SCBJ6Sygz1Dpl0wqjlhDEGGBP1GnsUVEL0p63hoG1fcj3fHynXi9NYO4nWOL+qQ==";
      };
    };
    "safe-buffer-5.1.2" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.1.2.tgz";
        sha512 = "Gd2UZBJDkXlY7GbJxfsE8/nvKkUEU1G38c1siN6QP6a9PT9MmHB8GnpscSmMJSoF8LOIrt8ud/wPtojys4G6+g==";
      };
    };
    "setprototypeof-1.1.1" = {
      name = "setprototypeof";
      packageName = "setprototypeof";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/setprototypeof/-/setprototypeof-1.1.1.tgz";
        sha512 = "JvdAWfbXeIGaZ9cILp38HntZSFSo3mWg6xGcJJsd+d4aRMOqauag1C63dJfDw7OaMYwEbHMOxEZ1lqVRYP2OAw==";
      };
    };
    "setprototypeof-1.2.0" = {
      name = "setprototypeof";
      packageName = "setprototypeof";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/setprototypeof/-/setprototypeof-1.2.0.tgz";
        sha512 = "E5LDX7Wrp85Kil5bhZv46j8jOeboKq5JMmYM3gVGdGH8xFpPWXUMsNrlODCrkoxMEeNi/XZIwuRvY4XNwYMJpw==";
      };
    };
    "source-map-0.6.1" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.6.1.tgz";
        sha512 = "UjgapumWlbMhkBgzT7Ykc5YXUT46F0iKu8SGXq0bcwP5dz/h0Plj6enJqjz1Zbq2l5WaqYnrVbwWOWMyF3F47g==";
      };
    };
    "source-map-support-0.5.6" = {
      name = "source-map-support";
      packageName = "source-map-support";
      version = "0.5.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map-support/-/source-map-support-0.5.6.tgz";
        sha512 = "N4KXEz7jcKqPf2b2vZF11lQIz9W5ZMuUcIOGj243lduidkf2fjkVKJS9vNxVWn3u/uxX38AcE8U9nnH9FPcq+g==";
      };
    };
    "statuses-1.5.0" = {
      name = "statuses";
      packageName = "statuses";
      version = "1.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/statuses/-/statuses-1.5.0.tgz";
        sha1 = "161c7dac177659fd9811f43771fa99381478628c";
      };
    };
    "toidentifier-1.0.0" = {
      name = "toidentifier";
      packageName = "toidentifier";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/toidentifier/-/toidentifier-1.0.0.tgz";
        sha512 = "yaOH/Pk/VEhBWWTlhI+qXxDFXlejDGcQipMlyxda9nthulaxLZUNcUqFxokp0vcYnvteJln5FNQDRrxj3YcbVw==";
      };
    };
    "tsscmp-1.0.6" = {
      name = "tsscmp";
      packageName = "tsscmp";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/tsscmp/-/tsscmp-1.0.6.tgz";
        sha512 = "LxhtAkPDTkVCMQjt2h6eBVY28KCjikZqZfMcC15YBeNjkgUpdCfBu5HoiOTDu86v6smE8yOjyEktJ8hlbANHQA==";
      };
    };
    "type-is-1.6.18" = {
      name = "type-is";
      packageName = "type-is";
      version = "1.6.18";
      src = fetchurl {
        url = "https://registry.npmjs.org/type-is/-/type-is-1.6.18.tgz";
        sha512 = "TkRKr9sUTxEH8MdfuCSP7VizJyzRNMjj2J2do2Jr3Kym598JVdEksuzPQCnlFPW4ky9Q+iA+ma9BGm06XQBy8g==";
      };
    };
    "typescript-4.2.4" = {
      name = "typescript";
      packageName = "typescript";
      version = "4.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/typescript/-/typescript-4.2.4.tgz";
        sha512 = "V+evlYHZnQkaz8TRBuxTA92yZBPotr5H+WhQ7bD3hZUndx5tGOa1fuCgeSjxAzM1RiN5IzvadIXTVefuuwZCRg==";
      };
    };
    "uuid-3.2.1" = {
      name = "uuid";
      packageName = "uuid";
      version = "3.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/uuid/-/uuid-3.2.1.tgz";
        sha512 = "jZnMwlb9Iku/O3smGWvZhauCf6cvvpKi4BKRiliS3cxnI+Gz9j5MEpTz2UFuXiKPJocb7gnsLHwiS05ige5BEA==";
      };
    };
    "vary-1.1.2" = {
      name = "vary";
      packageName = "vary";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/vary/-/vary-1.1.2.tgz";
        sha1 = "2299f02c6ded30d4a5961b0b9f74524a18f634fc";
      };
    };
    "weak-map-1.0.5" = {
      name = "weak-map";
      packageName = "weak-map";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/weak-map/-/weak-map-1.0.5.tgz";
        sha1 = "79691584d98607f5070bd3b70a40e6bb22e401eb";
      };
    };
    "ylru-1.2.1" = {
      name = "ylru";
      packageName = "ylru";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ylru/-/ylru-1.2.1.tgz";
        sha512 = "faQrqNMzcPCHGVC2aaOINk13K+aaBDUPjGWl0teOXywElLjyVAB6Oe2jj62jHYtwsU49jXhScYbvPENK+6zAvQ==";
      };
    };
  };
  args = {
    name = "manifold-gas-service";
    packageName = "manifold-gas-service";
    version = "1.0.2";
    src = ./.;
    dependencies = [
      sources."@types/accepts-1.3.5"
      sources."@types/body-parser-1.19.0"
      sources."@types/collections-5.0.0"
      sources."@types/connect-3.4.34"
      sources."@types/content-disposition-0.5.3"
      sources."@types/cookies-0.7.6"
      sources."@types/express-4.17.11"
      sources."@types/express-serve-static-core-4.17.19"
      sources."@types/http-assert-1.5.1"
      sources."@types/http-errors-1.8.0"
      sources."@types/keygrip-1.0.2"
      sources."@types/koa-2.13.1"
      sources."@types/koa-compose-3.2.5"
      sources."@types/koa2-cors-2.0.1"
      sources."@types/mime-1.3.2"
      sources."@types/node-14.14.37"
      sources."@types/node-fetch-2.5.7"
      sources."@types/qs-6.9.6"
      sources."@types/range-parser-1.2.3"
      sources."@types/serve-static-1.13.9"
      (sources."accepts-1.3.7" // {
        dependencies = [
          sources."mime-db-1.47.0"
          sources."mime-types-2.1.30"
        ];
      })
      sources."any-promise-1.3.0"
      sources."asynckit-0.4.0"
      sources."buffer-from-1.1.1"
      (sources."cache-content-type-1.0.1" // {
        dependencies = [
          sources."mime-db-1.47.0"
          sources."mime-types-2.1.30"
        ];
      })
      sources."co-4.6.0"
      sources."collections-5.1.2"
      sources."combined-stream-1.0.8"
      sources."content-disposition-0.5.3"
      sources."content-type-1.0.4"
      sources."cookies-0.8.0"
      sources."debug-3.1.0"
      sources."deep-equal-1.0.1"
      sources."delayed-stream-1.0.0"
      sources."delegates-1.0.0"
      sources."depd-2.0.0"
      sources."destroy-1.0.4"
      sources."ee-first-1.1.1"
      sources."encodeurl-1.0.2"
      sources."escape-html-1.0.3"
      sources."ethereumjs-blockstream-7.0.0"
      sources."form-data-3.0.0"
      sources."fresh-0.5.2"
      (sources."http-assert-1.4.1" // {
        dependencies = [
          sources."depd-1.1.2"
          sources."http-errors-1.7.3"
        ];
      })
      (sources."http-errors-1.8.0" // {
        dependencies = [
          sources."depd-1.1.2"
          sources."setprototypeof-1.2.0"
        ];
      })
      sources."immutable-3.8.2"
      sources."inherits-2.0.4"
      sources."is-generator-function-1.0.8"
      sources."keygrip-1.1.0"
      sources."koa-2.13.1"
      sources."koa-compose-4.1.0"
      (sources."koa-convert-1.2.0" // {
        dependencies = [
          sources."koa-compose-3.2.1"
        ];
      })
      sources."koa2-cors-2.0.5"
      sources."media-typer-0.3.0"
      sources."mime-db-1.30.0"
      sources."mime-types-2.1.17"
      sources."ms-2.0.0"
      sources."negotiator-0.6.2"
      sources."node-fetch-2.6.1"
      sources."on-finished-2.3.0"
      sources."only-0.0.2"
      sources."parseurl-1.3.3"
      sources."safe-buffer-5.1.2"
      sources."setprototypeof-1.1.1"
      sources."source-map-0.6.1"
      sources."source-map-support-0.5.6"
      sources."statuses-1.5.0"
      sources."toidentifier-1.0.0"
      sources."tsscmp-1.0.6"
      (sources."type-is-1.6.18" // {
        dependencies = [
          sources."mime-db-1.47.0"
          sources."mime-types-2.1.30"
        ];
      })
      sources."typescript-4.2.4"
      sources."uuid-3.2.1"
      sources."vary-1.1.2"
      sources."weak-map-1.0.5"
      sources."ylru-1.2.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
    };
    production = true;
    bypassCache = true;
    reconstructLock = false;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
